#cloud-config
write_files:
  - owner: root:root
    path: /opt/setup_lustre.sh
    content: |
      sh -c 'cat >/etc/yum.repos.d/lustre.repo' <<EOF
      [lustre-server]
      name=CentOS-$releasever - Lustre
      baseurl=https://downloads.hpdd.intel.com/public/lustre/latest-feature-release/el7/server/
      gpgcheck=0

      [e2fsprogs]
      name=CentOS-$releasever - Ldiskfs
      baseurl=https://downloads.hpdd.intel.com/public/e2fsprogs/latest/el7/
      gpgcheck=0

      [lustre-client]
      name=CentOS-$releasever - Lustre
      baseurl=https://downloads.hpdd.intel.com/public/lustre/latest-feature-release/el7/client/
      gpgcheck=0
      EOF


      yum install -y e2fsprogs

      wget https://downloads.whamcloud.com/public/lustre/lustre-2.13.0/el7.7.1908/server/RPMS/x86_64/kernel-3.10.0-1062.1.1.el7_lustre.x86_64.rpm
      wget https://downloads.whamcloud.com/public/lustre/lustre-2.13.0/el7.7.1908/server/RPMS/x86_64/lustre-2.13.0-1.el7.x86_64.rpm
      wget https://downloads.whamcloud.com/public/lustre/lustre-2.13.0/el7.7.1908/server/RPMS/x86_64/kmod-lustre-2.13.0-1.el7.x86_64.rpm
      wget https://downloads.whamcloud.com/public/lustre/lustre-2.13.0/el7.7.1908/server/RPMS/x86_64/kmod-lustre-osd-ldiskfs-2.13.0-1.el7.x86_64.rpm
      wget https://downloads.whamcloud.com/public/lustre/lustre-2.13.0/el7.7.1908/server/RPMS/x86_64/lustre-osd-ldiskfs-mount-2.13.0-1.el7.x86_64.rpm
      wget https://downloads.whamcloud.com/public/lustre/lustre-2.13.0/el7.7.1908/server/RPMS/x86_64/lustre-tests-2.13.0-1.el7.x86_64.rpm

      yum install -y kernel-3.10.0-1062.1.1.el7_lustre.x86_64.rpm
      yum install -y kmod*
      yum install -y lustre*
  - owner: root:root
    path: /opt/setup_mdt.sh
    content: |
      sudo mkdir /lustre-mdt0
      echo "/dev/sdc                                /lustre-mdt0               lustre  defaults,_netdev        0 0" | sudo tee -a /etc/fstab
      sudo mount /dev/sdc
runcmd:
  - bash /opt/setup_lustre.sh
  - reboot 
