#cloud-config
write_files:
  - owner: root:root
    path: /opt/setup_lustre_client.sh
    content: |

  - owner: root:root
    path: /opt/setup_mdt.sh
    content: |
      sudo mkdir /lustre-mdt0
      echo "/dev/sdc                                /lustre-mdt0               lustre  defaults,_netdev        0 0" | sudo tee -a /etc/fstab
      sudo mount /dev/sdc
runcmd:
  - bash /opt/setup_lustre.sh
  - reboot 
